before_script:
  - echo "Running before_script. Current directory "
  - pwd

stages:
  - build
  - test
  
build lama on draco:
    stage: build
    before_script:
      - module load tools/cmake/3.5.2
      - module load gcc/4.9.1
    variables:
      USE_CUDA: 0
    script:
      - mkdir scai/build
      - cd scai/build
      - cmake -DUSE_CUDA=0 ..
      - make -j4
    tags:
      - draco
