stages:
  # Provides a basic sanity check for a small portion of the LAMA library.
  # Is quick to build and run, and it might capture e.g. certain differences
  # in environment
  - basic build test
  # Build, test and install the entire LAMA library. Most jobs run in this stage
  - build test install
  
variables:
  BUILD_THREADS: 8
  BUILD_DIR: $CI_PROJECT_DIR/build
  INSTALL_DIR: $CI_PROJECT_DIR/installed
  OMP_NUM_THREADS: 8

  # Default configuration for LAMA build
  LAMA_BUILD_TYPE: Release
  USE_OPENMP: 1
  USE_CUDA: 0
  USE_JAVA: 0
  USE_MPI: 0
  USE_METIS: 0
  USE_BOOST_TEST: 1

  # For Boost versions that are recent enough, make the output colored
  BOOST_TEST_COLOR_OUTPUT: 1

.before_every_job: &before_every_job
    |
      echo -e "Build directory: $BUILD_DIR"
      echo -e "Install directory: $INSTALL_DIR"

.build test install template: &build_test_install_template
  script:
    - mkdir $BUILD_DIR
    - cd $BUILD_DIR
    - env
    - set -x
    # Note: eval is necessary to expand EXTRA_CMAKE_OPTS correctly
    - >
        eval cmake ../scai
        -DUSE_OPENMP=$USE_OPENMP
        -DUSE_CUDA=$USE_CUDA
        -DUSE_JAVA=$USE_JAVA
        -DUSE_MPI=$USE_MPI
        -DUSE_METIS=$USE_METIS
        -DCMAKE_INSTALL_PREFIX=$INSTALL_DIR
        -DUSE_BOOST_TEST=$USE_BOOST_TEST
        -DCMAKE_BUILD_TYPE=$LAMA_BUILD_TYPE
        "$EXTRA_CMAKE_OPTS"
    - make -j$BUILD_THREADS
    - make -j$BUILD_THREADS examples tests
    - eval python run_tests.py --output_dir testoutput "$RUN_TESTS_ARGS"
    - make install
  artifacts:
    paths:
    - testoutput/report.html
    - testoutput/
    expire_in: 1 week

###############################################################
# CONFIGURATIONS INTENDED TO RUN ON EVERY COMMIT TO ANY BRANCH
###############################################################

common basic build serial gcc 4.9.1 (debug):
  # This is the most basic build configuration.
  # It is only intended as a quick and basic sanity check,
  # so that using compute resources for running the full
  # configurations can be avoided if this one fails
  <<: *build_test_install_template
  stage: basic build test
  before_script:
    - *before_every_job
    - module load tools/cmake/3.5.2 tools/python/2.7.14
    - module unload gcc
    - module load gcc/4.9.1
  variables:
    LAMA_BUILD_TYPE: Debug
    USE_OPENMP: 0
    USE_CUDA: 0
    OMP_NUM_THREADS: 1
    BOOST_ROOT: /scaihome/lama/boost_test_1_65_1_gcc_4_9_1
    # Note the SCAI_MODULES definition
    EXTRA_CMAKE_OPTS: -DBoost_NO_BOOST_CMAKE=1 -DSCAI_MODULES=common
    RUN_TESTS_ARGS: --tests commonTest
  tags:
    - draco

serial gcc 4.9.1 (release):
  <<: *build_test_install_template
  stage: build test install
  before_script:
    - *before_every_job
    - module load tools/cmake/3.5.2 tools/python/2.7.14
    - module unload gcc
    - module load gcc/4.9.1
  variables:
    LAMA_BUILD_TYPE: Release
    USE_CUDA: 0
    OMP_NUM_THREADS: 1
    # It seems to be necessary to specifically specify the Boost installation
    BOOST_ROOT: /scaihome/lama/boost_test_1_65_1_gcc_4_9_1
    EXTRA_CMAKE_OPTS: -DBoost_NO_BOOST_CMAKE=1
  tags:
    - draco

serial gcc 4.9.1 (debug):
  <<: *build_test_install_template
  stage: build test install
  before_script:
    - *before_every_job
    - module load tools/cmake/3.5.2 tools/python/2.7.14
    - module unload gcc
    - module load gcc/4.9.1
  variables:
    LAMA_BUILD_TYPE: Debug
    USE_CUDA: 0
    OMP_NUM_THREADS: 1
    # It seems to be necessary to specifically specify the Boost installation
    BOOST_ROOT: /scaihome/lama/boost_test_1_65_1_gcc_4_9_1
    EXTRA_CMAKE_OPTS: -DBoost_NO_BOOST_CMAKE=1
  tags:
    - draco

parallel gcc 6.3.0 (release):
  <<: *build_test_install_template
  stage: build test install
  before_script:
    - *before_every_job
    - module load tools/cmake/3.5.2 tools/python/2.7.14
    - module unload gcc
    - module load gcc/6.3.0
  variables:
    LAMA_BUILD_TYPE: Release
    USE_CUDA: 0
    OMP_NUM_THREADS: 4
    # It seems to be necessary to specifically specify the Boost installation
    BOOST_ROOT: /scaihome/lama/boost_test_1_65_1
    EXTRA_CMAKE_OPTS: -DBoost_NO_BOOST_CMAKE=1
  tags:
    - draco


##################################################################
# CONFIGURATIONS INTENDED TO RUN ON EVERY COMMIT TO MASTER/DEVELOP
##################################################################

parallel gcc 5.4.0 (release):
  <<: *build_test_install_template
  stage: build test install
  before_script:
    - *before_every_job
    - module load tools/cmake/3.5.2 tools/python/2.7.14
    - module unload gcc
    - module load gcc/5.4.0
  variables:
    LAMA_BUILD_TYPE: Release
    USE_CUDA: 0
    OMP_NUM_THREADS: 4
    # It seems to be necessary to specifically specify the Boost installation
    BOOST_ROOT: /scaihome/lama/boost_test_1_65_1
    EXTRA_CMAKE_OPTS: -DBoost_NO_BOOST_CMAKE=1
  tags:
    - draco
  only:
    - master
    - develop

sanitized parallel gcc 6.3.0:
  <<: *build_test_install_template
  stage: build test install
  before_script:
    - *before_every_job
    - module load tools/cmake/3.5.2 tools/python/2.7.14
    - module unload gcc
    - module load gcc/6.3.0
  variables:
    LAMA_BUILD_TYPE: Debug
    USE_CUDA: 0
    OMP_NUM_THREADS: 4
    # It seems to be necessary to specifically specify the Boost installation
    BOOST_ROOT: /scaihome/lama/boost_test_1_65_1
    UBSAN_OPTIONS: print_stacktrace=1
    # We currently have some tests which try to allocate too much memory,
    # expecting to receive an exception. ASAN will by default not allow returning
    # null from the allocator, so we have to instruct it to ignore it.
    ASAN_OPTIONS: allocator_may_return_null=true
    EXTRA_CMAKE_OPTS: >
        -DBoost_NO_BOOST_CMAKE=1
        -DADDITIONAL_CXX_FLAGS="-fsanitize=undefined -fno-sanitize-recover=all -fno-omit-frame-pointer"
        -DADDITIONAL_LINKER_FLAGS="-fsanitize=undefined -fno-sanitize-recover=all"
  tags:
    - draco
  only:
    - master
    - develop
