stages:
  # Provides a basic sanity check for a small portion of the LAMA library.
  # Is quick to build and run, and it might capture e.g. certain differences
  # in environment
  - basic build test
  # Build, test and install the entire LAMA library. Most jobs run in this stage
  - build test install
  
variables:
  BUILD_THREADS: 8
  BUILD_DIR: $CI_PROJECT_DIR/build
  INSTALL_DIR: $CI_PROJECT_DIR/installed
  OMP_NUM_THREADS: 8

  # Default configuration for LAMA build
  LAMA_BUILD_TYPE: Release
  USE_OPENMP: 1
  USE_CUDA: 0
  USE_JAVA: 0
  USE_MPI: 0
  USE_METIS: 0
  USE_BOOST_TEST: 1

  # For Boost versions that are recent enough, make the output colored
  BOOST_TEST_COLOR_OUTPUT: 1

.before_every_job: &before_every_job
    |
      echo -e "Build directory: $BUILD_DIR"
      echo -e "Install directory: $INSTALL_DIR"

.build test install template: &build_test_install_template
  script:
    - mkdir $BUILD_DIR
    - cd $BUILD_DIR
    - env
    - set -x
    # Note: eval is necessary to expand EXTRA_CMAKE_OPTS correctly
    - >
        eval cmake3 ../scai
        -DUSE_OPENMP=$USE_OPENMP
        -DUSE_CUDA=$USE_CUDA
        -DUSE_JAVA=$USE_JAVA
        -DUSE_MPI=$USE_MPI
        -DUSE_METIS=$USE_METIS
        -DCMAKE_INSTALL_PREFIX=$INSTALL_DIR
        -DUSE_BOOST_TEST=$USE_BOOST_TEST
        -DCMAKE_BUILD_TYPE=$LAMA_BUILD_TYPE
        -DSCAI_CMAKE_VERBOSE=1
        "$EXTRA_CMAKE_OPTS"
    - make -j$BUILD_THREADS
    - make -j$BUILD_THREADS examples tests
    - eval python run_tests.py --output_dir $BUILD_DIR/testoutput --temp_dir tmp "$RUN_TESTS_ARGS"
    - make install > $CI_PROJECT_DIR/make_install_output.txt
  after_script:
    - mv $BUILD_DIR/testoutput $CI_PROJECT_DIR/testoutput
    - cp $CI_PROJECT_DIR/testoutput/report.html $CI_PROJECT_DIR/test_report.html
  artifacts:
    paths:
    # Note: These paths should be relative, otherwise weird things may happen!
    - testoutput/
    - test_report.html
    - make_install_output.txt
    expire_in: 1 week
    when: always
  # By default, artifacts from the previous stage are passed through. We don't want this!
  dependencies: []

###############################################################
# CONFIGURATIONS INTENDED TO RUN ON EVERY COMMIT TO ANY BRANCH
###############################################################

gpu (release):
  <<: *build_test_install_template
  stage: build test install
  before_script:
    - *before_every_job
  variables:
    LAMA_BUILD_TYPE: Release
    USE_CUDA: 1
    USE_MPI: 1
    OMP_NUM_THREADS: 1
    # It seems to be necessary to specifically specify the Boost installation
    BOOST_ROOT: /home/brandes/local/boost_test_1_65_1_gcc_4_9_1
    MPI_HOME: /usr/lib64/openmpi
    EXTRA_CMAKE_OPTS: -DBoost_NO_BOOST_CMAKE=1 -DBoost_NO_SYSTEM_PATHS=1
  tags:
    - bliss
