#!/bin/sh

ASTYLE=no
if test x$ASTYLE = "xno"; then
    ASTYLE=astyle
fi

OUTPUT=$($ASTYLE --version 2>&1 | cat)

# deduce the version
VERSION=${OUTPUT#Artistic Style Version }

OPTIONS="--style=ansi \
--indent=spaces=4 \
--indent-preprocessor \
--indent-switches \
--break-blocks \
--convert-tabs \
--pad-oper \
--pad-header \
--pad-paren-in \
--add-brackets \
--align-pointer=type"

# The following options are no more used:
# --delete-empty-lines \
# --keep-one-line-statements \

CMD="$ASTYLE $OPTIONS $@"
echo $CMD
exec $CMD
