set ( SCAI_VERSION_NAME "Alpamayo" )
set ( SCAI_COPYRIGHT_YEAR 2016 )

## with CMake >= 3.0.2 this can be set in project definition, e.g. project( scai_common VERSION 1.0.0 LANGUAGES CXX )

set ( SCAI_LAMA_ALL_VERSION   2.0.0 )
set ( SCAI_COMMON_VERSION     1.0.0 )
set ( SCAI_LOGGING_VERSION    1.0.0 )
set ( SCAI_TRACING_VERSION    1.0.0 )
set ( SCAI_TASKING_VERSION    1.0.0 )
set ( SCAI_HMEMO_VERSION      1.0.0 )
set ( SCAI_KREGISTRY_VERSION  1.0.0 )
set ( SCAI_BLASKERNEL_VERSION 1.0.0 )
set ( SCAI_LAMA_VERSION       2.0.0 )
set ( SCAI_SOLVER_VERSION     1.0.0 )